encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:entry>", views.get_entrypage, name="entry"),
    path("search/", views.search_entry, name="search"),
    path("new/", views.new_page, name="new"),
    path("edit/", views.edit_page, name="edit"),
    path("save/", views.save_page, name="save"),
    path("random/", views.random_page, name="random"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from random import choice

from . import util

import markdown2


class SearchForm(forms.Form):
    search_query = forms.CharField(label="",required=False, widget=forms.TextInput (attrs={'placeholder':'Search Encyclopedia'}))


def index(request):
    form = SearchForm()

    entries = util.list_entries()
    return render(request, "encyclopedia/index.html", {
        "entries": entries,
        "form": form
    })


def get_entrypage(request, entry):
    form = SearchForm()

    display = util.get_entry(entry)

    if display == None:
        return render(request, "encyclopedia/error-page.html", {
            "message":"This page does not exist..",
            "form": form
        })
    else:
        return render(request, "encyclopedia/entrypage.html", {
            "title": entry,
            "display": markdown2.markdown(display),
            "form": form
        })


def search_entry(request):

    if request.method == "POST":

        form = SearchForm(request.POST)

        if form.is_valid():

            search_query = form.cleaned_data["search_query"]
            entry_list = util.get_entry(search_query)

            if entry_list is not None:
                return get_entrypage(request, search_query)
            else:
                search_results = []
                for entry in util.list_entries():
                    if search_query.lower() in entry.lower():
                        search_results.append(entry)
                if search_results:
                    return render(request, "encyclopedia/search_results.html", {
                        "search_results": search_results,
                        "form": form
                    })
                else:
                    return render(request, "encyclopedia/error-page.html", {
                        "message": "No search results found..",
                        "form": form
                    })


def new_page(request):
    form = SearchForm()

    if request.method == "GET":
        return render(request, "encyclopedia/newpage.html", {
            "form": form
        })
    else:
        entry = request.POST['title']
        display = request.POST['md_content']
        if util.get_entry(entry) is not None:
            return render(request, "encyclopedia/error-page.html", {
                "message":"This entry already exists..",
                "form": form
            })
        else:
            util.save_entry(entry, display)
            return get_entrypage(request, entry)

def edit_page(request):
    form = SearchForm()

    if request.method == "POST":
        entry = request.POST['title']
        display = util.get_entry(entry)
        return render(request, "encyclopedia/editpage.html", {
            "title": entry,
            "content": display,
            "form": form
        })

def save_page(request):
    form = SearchForm()

    if request.method == "POST":
        entry = request.POST['title']
        display = request.POST['md_content']
        util.save_entry(entry, display)
        return get_entrypage(request, entry)

def random_page(request):
    form = SearchForm()

    entries = util.list_entries()
    entry = choice(entries)
    display = util.get_entry(entry)
    return get_entrypage(request, entry)

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit Existing Page</h1>

    <form action="{% url 'encyclopedia:save' %}" method="POST">
        {% csrf_token %}
        <label> Edit your page title: </label>
        <input type="text" name="title" placeholder="Insert title" value="{{ title }}">
        <br><br>
        <label> Edit your Markdown content: </label>
        <br>
        <textarea name="md_content" rows="8" cols="80">{{content}}</textarea>
        <br>
        <input type="submit" value="Save your changes">
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/entrypage.html
{% extends "encyclopedia/layout.html" %}
{% block title %}

    {{ title }}

{% endblock %}

{% block body %}

    {{ display|safe }}

    <br>

    <form action="{% url 'encyclopedia:edit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ title }}">
        <input type="submit" value="Edit this page">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/error-page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1> Error: </h1>

    <br>

    <h2> {{ message }} </h2>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    {{form}}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>

    <form action="{% url 'encyclopedia:new' %}" method="POST">
        {% csrf_token %}
        <label> Add your page title: </label>
        <input type="text" name="title" placeholder="Insert title">
        <br><br>
        <label> Add your Markdown content: </label>
        <br>
        <textarea name="md_content" rows="8" cols="80"></textarea>
        <br>
        <input type="submit" value="Create New Page">
    </form>


{% endblock %}

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for result in results %}
            <li><a href="{% url 'encyclopedia:search' %}">{{ result }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in search_results %}
            <li><a href="{% url 'encyclopedia:entry' entry=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}